name: "Build - master and PR"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_java8_quarkus_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Check Wildcards
        run: |
          if [ $(git grep import | grep '\*;' | grep -E -v '(.mvn/|README.md|CONTRIBUTING.md)' | wc -l) != 0 ]; then
            echo "Please don't use star imports in your Java files: "
            git grep import | grep '\*;' | grep -E -v '(.mvn/|README.md|CONTRIBUTING.md)'
            exit 1
          fi
      - name: Install JDK 1.8
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk8'
      - name: Build Quarkus master
          run: |
            git clone https://github.com/quarkusio/quarkus.git \
            && cd quarkus \
            && mvn -B clean install -DskipTests -DskipITs -DskipDocs
            - name: Build with Maven
              run: export LANG=en_US && mvn -B clean install
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  build_java11_quarkus_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK 11
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk11'
      - name: Build Quarkus master
        run: |
          git clone https://github.com/quarkusio/quarkus.git \
          && cd quarkus \
          && mvn -B clean install -DskipTests -DskipITs -DskipDocs
      - name: Build with Maven
        run: export LANG=en_US && mvn -B clean install -Pnative -Dquarkus.native.container-build=true

  build_java11_quarkus_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK 11
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk11'
      - name: Update Quarkus version
        run: |
          mvn versions:set-property -Dproperty="quarkus.version" -DnewVersion="1.3.2.Final" -DgenerateBackupPoms=false
      - name: Build with Maven
        run: export LANG=en_US && mvn -B clean install -Pnative -Dquarkus.native.container-build=true